name: Deploy Loader

on: [push, pull_request]

jobs:
  deploy_loader:
    if: startsWith(github.ref, 'refs/tags/rdb_loader')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '2.x'
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          release-manager
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and publish Loader
      run: .github/deploy.sh rdb_loader $GITHUB_REF
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
