name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install release manager
      run: pip install --user release-manager==0.4.1
    - name: Compare SBT version with git tag
      run: .github/check_tag.sh ${GITHUB_REF##*/}
    - name: Build and publish Shredder
      run: ./github/deploy.sh rdb_shredder ${GITHUB_REF##*/}
    - name: Build and publish Loader
      run: ./github/deploy.sh rdb_loader ${GITHUB_REF##*/}


